### ISSUE TITLE
ads_blocked_today rolling over every hour

### ISSUE THREAD

**Issue by RandomActPG** [janw/pi-hole-influx#17]
Looking at the pihole logs and influxdb data, it looks like the ads_blocked_today value rolls over on the hour, and is actually a rolling "past 24 hours" not "today".

Is there a good solution, either at the code level, or in grafana, to work around this? Currently I get one entry of anywhere from -600 to -900 on the hour as the value drops down.

**Comment by janw** [comment]
You are correct, and this has bothered me as well. I have so far not found an elegant solution to alleviate this, and believe this should be fixed in Pi-hole itself.

An alternative display option in Grafana would be to have a cumulative sum of non-negative differences, of the same field, i.e. something like "Cumulative Queries over selected Time Range":

```sql
SELECT cumulative_sum("non_negative_difference") FROM (
    SELECT non_negative_difference("dns_queries_today") 
    FROM "pihole" WHERE ("host" =~ /^$host$/) AND $timeFilter
)
```

Looking like so:

<img width="1102" alt="screenshot 2019-03-03 at 19 00 58" src="https://user-images.githubusercontent.com/1690502/53699278-bfbb3400-3de6-11e9-8a50-63666e14b281.png">

I bet there should be a way to base the initial value on the cumulative queries over the entirety of the DB column as well, I just didn't try that so far.

Does that help? :)
