### ISSUE TITLE
Support for influxDB SSL connection?

### ISSUE THREAD

**Issue by djdubd** [janw/pi-hole-influx#39]
Sorry if I missed this, as I looked in the closed issues and didn't find it. Is it possible to connect to an influxDB that is using SSL? I have my influxDB setup with a trusted (not self signed) certificate. When I run "python3 piholeinflux.py" I receive a connection error:

```
raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

```
In my user.toml file I have the following for the host:

`influxdb_host = "[INFLUXDB IP ADDRESS]"`

Please advise, thank you!

**Comment by djdubd** [comment]
Nevermind, I think I see it now, should I have configured the default.toml file instead?

https://github.com/janw/pi-hole-influx/blob/master/default.toml

If I use this config, do I still need the "user.toml" file as well?

**Comment by Procuria** [comment]
Thank you very much @djdubd for pointing into the right direction and I may add that adding the INfluxDB-Creds works very well too there.
@janw thank you very much for this fine piece of code but I'd like to ask too if the user.toml is still needed?

**Comment by janw** [comment]
Hey folks, thanks for your feedback. It's greatly appreciated!

Theoretically you could just update the `default.toml` to match your settings, that's right. But since that file is checked into Git, I personally prefer using the `user.toml` for the settings that deviate from the defaults as to not have a dirty workspace / accidental commits of credentials.

Of course all options from `defaults` can be copied to `user` and modified to your needs, they will then override the defaults. I agree that this is not very clear in the readme, I will update that (and possibly the daemon it self as well) soon.

**Comment by janw** [comment]
Closing this in favor of #42. Thanks again.
