### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by thiagolocatelli** [janw/pi-hole-influx#6]
Could you create a docker image for this app?

**Comment by janw** [comment]
Hey @thiagolocatelli! Sure, that's a great idea; I'm already working on that. One thing I'm still figuring out is how to make the configuration easy. I'll probably add support for setting them via Environment Variables which goes well with Docker, and the 12-factor methodology.

Stay tuned! 👋

**Comment by rzae** [comment]
Hi,

Thanks for docke image.

I run the docker image in synology and when i start caintainer, i have this error:
 raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.1.32:8888/admin/api.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2de62b69b0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

**Comment by janw** [comment]
@rzae If your given output is unmodified, your problem is that `//192.168.1.32:8888/admin/api.php` is not a valid url. Misses `http:` in front of it.

**Comment by adznon** [comment]
Hi Janw,

Am recieving the below error when trying to start pi-hole-influx. As you can see i have http in the setting so not sure what else is wrong.

Any ideas ?

Using config: {'INFLUX_HOST': '10.2.10.248', 'INFLUX_PORT': '8086', 'INFLUX_USERNAME': '**username**', 'INFLUX_PASSWORD': '**Password**', 'INFLUX_DATABASE': 'telegraf', 'PIHOLE_API': 'http://10.2.10.103/admin/api.php', 'PIHOLE_INSTANCE_NAME': 'Plexy_Secure=http://10.2.10.103/admin/api.php', 'REPORTING_INTERVAL': 500}

Failed, to report to InfluxDB: HTTPConnectionPool(host='10.2.10.103', port=80): Max retries exceeded with url: /admin/api.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x14ac93491a20>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
