### ISSUE TITLE
Recent update to pihole causes issues with python script

### ISSUE THREAD

**Issue by Guyverix** [janw/pi-hole-influx#62]
I just completed an upgrade from Ubuntu 18 to Ubuntu 20 and ran across this problem after getting Pihole updated..
The toml file may need to be changed to reflect API keys, as well as referencing summaryRaw in the toml.  I did not see this specifically in your readme, so figured I should mention it.  this is with the latest version of Pihole 
```
Pi-hole [v5.14.2](https://github.com/pi-hole/pi-hole/releases/v5.14.2) FTL [v5.20](https://github.com/pi-hole/FTL/releases/v5.20) Web Interface [v5.18](https://github.com/pi-hole/AdminLTE/releases/v5.18)
```

I ended up having to change my instances value to this to get the script to run:
```
instances="localhost=http://192.168.15.176/admin/api.php?auth=API_KEY_FROM_FILE_OR_GUI&summaryRaw"
```
Previously this was working:
 ```
instances="localhost=http://127.0.0.1/admin/api.php"
```
Not sure if this is related to the OS upgrade due to PI-Hole not allowing the update on Ubuntu 18, or if this is really legit due to the upgrade of Pihole itself but felt I should let you know that the readme may need to be updated to better reflect this.

**Comment by pluim003** [comment]
This is indeed due to changes in pi-hole. So indeed the config should look like (snippet from docker-compose.yml):

 PIHOLE_INSTANCES: "pihole=http://10.0.0.150:8100/admin/api.php?summaryRaw&auth=c29e51f1afef44f4bf5f4015610ccc469d526a2bc37fafbff42b845c78521a11"

This value can be obtained from setupVars.conf in your pihole-configuration (value WEBPASSWORD) .

It's mentioned in https://pi-hole.net/blog/2022/11/17/upcoming-changes-authentication-for-more-api-endpoints-required/#page-content 

A few months ago I moved to another repo, modified this for use with influxdb2. Dunno anymore what the main reason was.

**Comment by rubenixnagios** [comment]
> This is indeed due to changes in pi-hole. So indeed the config should look like (snippet from docker-compose.yml):
> 
> PIHOLE_INSTANCES: "pihole=http://10.0.0.150:8100/admin/api.php?summaryRaw&auth=c29e51f1afef44f4bf5f4015610ccc469d526a2bc37fafbff42b845c78521a11"
> 
> This value can be obtained from setupVars.conf in your pihole-configuration (value WEBPASSWORD) .
> 
> It's mentioned in https://pi-hole.net/blog/2022/11/17/upcoming-changes-authentication-for-more-api-endpoints-required/#page-content
> 
> A few months ago I moved to another repo, modified this for use with influxdb2. Dunno anymore what the main reason was.

worked like a charm!! thanks so much!

**Comment by janw** [comment]
Thank you all for the discussion. I just did an overhaul and updated the daemon for InfluxDB v2 support, and proper authentication support for the Pi-hole API as well. Feel free to check it out :)
